name: Deploy AgPro Backend Local (Dev)

on:
  push:
    branches: [ dev ] #

jobs:
  deploy:
    runs-on: self-hosted # <--- Isso faz o GitHub usar a sua VM do VirtualBox
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 # Baixa o código da branch dev na VM

      - name: Docker Compose Deploy
        run: |
          # O Runner já coloca você dentro da pasta do projeto automaticamente
          # 1. Garante que o arquivo .env existe (ou usa um padrão de dev)
          if [ ! -f ".env" ]; then
            echo "Aviso: Arquivo .env não encontrado. Usando variáveis do sistema ou padrão."
          fi

          # 2. Sobe os containers rebuildando a imagem
          # Como você adicionou o usuário msdevs ao grupo docker, não precisa de sudo!
          docker-compose up -d --build