name: Deploy AgPro Backend Local (Dev)

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          clean: true # O GitHub vai limpar a pasta aqui

      - name: Recuperar o .env da pasta segura
        run: |
          # Copia o arquivo da pasta protegida para a pasta onde o código acabou de cair
          cp ~/projeto_secrets/.env .
          
          # Caso o arquivo não exista no backup, cria um vazio para não travar o docker
          if [ ! -f ".env" ]; then touch .env; fi

      - name: Docker Compose Deploy
        run: |
          # Agora o .env está presente e o docker vai subir com as variáveis certas
          docker-compose up -d --build