name: Deploy AgPro Backend Local (Dev)

on:
  push:
    branches: [ dev ] #

jobs:
  deploy:
    runs-on: self-hosted # <--- Isso faz o GitHub usar a sua VM do VirtualBox
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 # Baixa o código da branch dev na VM

      - name: Docker Compose Deploy
        run: |
          
          if [ -f ".env" ]; then mv .env $HOME/env_agepro_backup; fi
          
          # Limpa qualquer outro lixo para deixar a pasta 100% vazia (requisito do git clone)
              rm -rf ./* ./.[!.]* 2>/dev/null || true
          
          if [ -f "$HOME/env_agepro_backup" ]; then 
              mv $HOME/env_agepro_backup .env

          # 2. Sobe os containers rebuildando a imagem
          # Como você adicionou o usuário msdevs ao grupo docker, não precisa de sudo!
          docker-compose up -d --build